name: build

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build
      - name: List
        run: ls
      - name: test
        run: chmod +x conan && ./conan
      - uses: actions/upload-artifact@v2
        with:
          name: conan
          path: conan
